name: HaaV User Service Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
    - UserServiceAPI/**

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file UserServiceAPI/Dockerfile --tag ${DOCKER_USER}/userservice:latest
    - name: Push Docker image to Docker Hub
      run: docker push ${DOCKER_USER}/userservice:latest
